[build]
  command = "npm install && npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18.17.0" }

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_ENV = "production"
  CI = "true" 