[build]
  command = "npm install && cd netlify/functions && npm install && cd ../.. && npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18.17.0" }
  functions = "netlify/functions"

[dev]
  command = "npm run dev"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@ibm-cloud/watsonx-ai", "ibm-cloud-sdk-core"]
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true